CREATE TABLE ftp_users (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE ftp_log (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    message TEXT,
    username VARCHAR(50),
    pid MEDIUMINT UNSIGNED,
    host VARCHAR(100),
    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
